### ISSUE TITLE
Error when running npm start

### ISSUE THREAD

**Issue by allysir2** [out386/aria-telegram-mirror-bot#103]
node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. internal\modules\cjs\loader.js:1156:30
[DEBUG] Bot is starting...
error: [polling_error] {"code":"ETELEGRAM","message":"ETELEGRAM: 404 Not Found"}
error: [polling_error] {"code":"ETELEGRAM","message":"ETELEGRAM: 404 Not Found"}
error: [polling_error] {"code":"ETELEGRAM","message":"ETELEGRAM: 404 Not Found"}
error: [polling_error] {"code":"ETELEGRAM","message":"ETELEGRAM: 404 Not Found"}
error: [polling_error] {"code":"ETELEGRAM","message":"ETELEGRAM: 404 Not Found"}
error: [polling_error] {"code":"ETELEGRAM","message":"ETELEGRAM: 404 Not Found"}
error: [polling_error] {"code":"ETELEGRAM","message":"ETELEGRAM: 404 Not Found"}
error: [polling_error] {"code":"ETELEGRAM","message":"ETELEGRAM: 404 Not Found"}
error: [polling_error] {"code":"ETELEGRAM","message":"ETELEGRAM: 404 Not Found"}
error: [polling_error] {"code":"ETELEGRAM","message":"ETELEGRAM: 404 Not Found"}
error: [polling_error] {"code":"ETELEGRAM","message":"ETELEGRAM: 404 Not Found"}
error: [polling_error] {"code":"ETELEGRAM","message":"ETELEGRAM: 404 Not Found"}

**Comment by NandiyaLive** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.17.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mirror-bot@2.0.0~prestart: mirror-bot@2.0.0
6 silly lifecycle mirror-bot@2.0.0~prestart: no script for prestart, continuing
7 info lifecycle mirror-bot@2.0.0~start: mirror-bot@2.0.0
8 verbose lifecycle mirror-bot@2.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle mirror-bot@2.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/neranjanaprsd/aria-telegram-mirror-bot/node_modules/.bin:/usr/local/bi$
10 verbose lifecycle mirror-bot@2.0.0~start: CWD: /home/neranjanaprsd/aria-telegram-mirror-bot
11 silly lifecycle mirror-bot@2.0.0~start: Args: [ '-c',
11 silly lifecycle   'NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js' ]
12 silly lifecycle mirror-bot@2.0.0~start: Returned: code: 1  signal: null
13 info lifecycle mirror-bot@2.0.0~start: Failed to exec start script
14 verbose stack Error: mirror-bot@2.0.0 start: `NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid mirror-bot@2.0.0
16 verbose cwd /home/neranjanaprsd/aria-telegram-mirror-bot
17 error Linux 4.9.0-11-amd64
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v6.17.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error mirror-bot@2.0.0 start: `NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js`
22 error Exit status 1
23 error Failed at the mirror-bot@2.0.0 start script 'NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the mirror-bot package,

**Comment by begginer-123** [comment]
Install npm property by 'sudo apt-get install npm' if you are using cli. Search google for other installation methods .
