### ISSUE TITLE
Terminal doesn't show an authentication URL

### ISSUE THREAD

**Issue by MrMarvell0us** [out386/aria-telegram-mirror-bot#111]
```
A2C: Websocket opened. Bot ready.
gid: 98f55eac82bc2407 download:https://raw.githubusercontent.com/out386/aria-telegram-mirror-bot/master/README.md
98f55eac82bc2407: Completed. Filename: README.md. Starting upload.
/root/aria-telegram-mirror-bot/out/drive/drive-auth.js:33
    const clientSecret = credentials.installed.client_secret;
                                               ^

TypeError: Cannot read property 'client_secret' of undefined
    at authorize (/root/aria-telegram-mirror-bot/out/drive/drive-auth.js:33:48)
    at /root/aria-telegram-mirror-bot/out/drive/drive-auth.js:21:13
```
Bot stops right after after this.

**Comment by PrinceVergil** [comment]
@MrMarvell0us did you solved this?
