### ISSUE TITLE
npm start problem

### ISSUE THREAD

**Issue by hypercian** [out386/aria-telegram-mirror-bot#129]
Dear @out386 , Thanks for your job :x 

I get this error

I did same steps and the robot was working completely ok.

but on this vps not works

VPS : 
OS : CentOS 7
RAM 4
CPU 3 Core
HDD 300 GB

I searched in issues but no one of them doesn't works.

anyone can help ?

"
[root@static aria-telegram-mirror-bot]# sudo bash ./aria.sh
Aria2c daemon started
[root@static aria-telegram-mirror-bot]# sudo npm start

> mirror-bot@2.0.0 start /root/aria-telegram-mirror-bot
> npx typescript && NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js

npx: installed 1 in 2.749s
/root/aria-telegram-mirror-bot/node_modules/googleapis/build/src/googleapis.js:93
    async discoverAsync(url) {
          ^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/aria-telegram-mirror-bot/node_modules/googleapis/build/src/index.js:19:22)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/aria-telegram-mirror-bot/out/drive/drive-auth.js:6:22)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)

npm ERR! Linux 3.10.0-1160.11.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! mirror-bot@2.0.0 start: `npx typescript && NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mirror-bot@2.0.0 start script 'npx typescript && NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mirror-bot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npx typescript && NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mirror-bot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mirror-bot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/aria-telegram-mirror-bot/npm-debug.log
[root@static aria-telegram-mirror-bot]#
"

**Comment by out386** [comment]
No idea what that's about. It should have compiled anyway, try running `NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js`

**Comment by hypercian** [comment]
I did but don't works
anyway thank you bro ❤️❤️

**Comment by hypercian** [comment]
I changed my os to ubuntu 18 and my problem is solved 🤷‍♂️

**Comment by xingxp** [comment]
just run "node --max_old_space_size=128 ./out/index.js"
it will be fine.
