### ISSUE TITLE
Cannot find module 'node-telegram-bot-api'

### ISSUE THREAD

**Issue by iopxiang** [out386/aria-telegram-mirror-bot#27]
npm --max_old_space_size=128 start

> mirror-bot@1.0.0 start /root/aria-telegram-mirror-bot
> node index.js

module.js:478
    throw err;
    ^

Error: Cannot find module 'node-telegram-bot-api'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/aria-telegram-mirror-bot/index.js:1:83)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)

npm ERR! Linux 3.10.0-957.10.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "--max_old_space_size=128" "start"
npm ERR! node v6.16.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! mirror-bot@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mirror-bot@1.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mirror-bot package,
npm ERR! not with npm itself.
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mirror-bot
npm ERR! Or if that isn't available, you can get their info via:

**Comment by out386** [comment]
You forgot to run `npm install` first.

**Comment by iopxiang** [comment]
I have run it already, but this issue is still there

**Comment by iopxiang** [comment]
npm install
Killed.............] | fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/tough-cookie

**Comment by out386** [comment]
You seem to be using a VPS. How much RAM does it have? The bot itself can't upload large file with less than 1GB, and I'd expect npm to have problems, too. If it's a VPS, try increasing RAM, else use a larger swap.

**Comment by iopxiang** [comment]
f1-micro (1 vCPU, 0.6 GB memory) 
Ok, I upgrade it immediately.

**Comment by iopxiang** [comment]
node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. module.js:577:32
/root/aria-telegram-mirror-bot/drive/upload-file.js:114
        request(options, async function (error, response, body) {
                         ^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/aria-telegram-mirror-bot/drive/drive-upload.js:3:19)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/aria-telegram-mirror-bot/fs-walk.js:3:16)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
npm ERR! Linux 3.10.0-957.12.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "--max_old_space_size=128" "start"
npm ERR! node v6.16.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! mirror-bot@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mirror-bot@1.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mirror-bot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mirror-bot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mirror-bot
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /root/aria-telegram-mirror-bot/npm-debug.log

**Comment by Yash-Garg** [comment]
> aria-telegram-mirror-bot]# npm install
> Killed.............] | fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/tough-cookie

Tried running `npm install` with `sudo` ?

**Comment by out386** [comment]
Are you sure that you didn't make any changes to the source? There aren't any SyntaxErrors here.
