### ISSUE TITLE
error at npm

### ISSUE THREAD

**Issue by yogeshrb** [out386/aria-telegram-mirror-bot#3]
npm --max_old_space_size=128 start
> mirror-bot@1.0.0 start /home/yogesh/aria-telegram-mirror-bot
> node index.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'node-telegram-bot-api'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/yogesh/aria-telegram-mirror-bot/index.js:1:83)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mirror-bot@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mirror-bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-10-05T17_17_18_825Z-debug.log

**Comment by NandiyaLive** [comment]
npm WARN ws@7.3.0 requires a peer of bufferutil@^4.0.1 but none was installed.
npm WARN ws@7.3.0 requires a peer of utf-8-validate@^5.0.2 but none was installed.
npm WARN mirror-bot@1.0.0 No repository field.
