### ISSUE TITLE
help Please

### ISSUE THREAD

**Issue by destroyer19991** [out386/aria-telegram-mirror-bot#45]
> mirror-bot@1.1.0 start /root/aria-telegram-mirror-bot
> NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js

/root/aria-telegram-mirror-bot/node_modules/googleapis/build/src/googleapis.js:93
    async discoverAsync(url) {
          ^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/aria-telegram-mirror-bot/node_modules/googleapis/build/src/index.js:19:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/aria-telegram-mirror-bot/out/drive/drive-auth.js:5:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 5.0.0-17-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! mirror-bot@1.1.0 start: `NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mirror-bot@1.1.0 start script 'NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mirror-bot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mirror-bot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mirror-bot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/aria-telegram-mirror-bot/npm-debug.log

**Comment by out386** [comment]
Try `rm -rf node_modules && npm install`

**Comment by destroyer19991** [comment]
thanks fixed by updating node and reinstalling node modules
